### ISSUE TITLE
Delete buttons should use DELETE method and should ask for confirmation

### ISSUE THREAD

**Issue by nishanthvijayan** [nishanthvijayan/ERP#2]
The delete buttons in http://localhost:8000/forms/workflows/1/ (1 or some  other id) delete the corresponding item without asking for any confirmation.
This is not ideal.
Also delete buttons should use the DELETE method (similar to POST , GET etc).

**Comment by utkarshrpr** [comment]
@nishanthvijayan  Shall we close this issue?

**Comment by nishanthvijayan** [comment]
Closed via #70
