### ISSUE TITLE
Support for Date field

### ISSUE THREAD

**Issue by nishanthvijayan** [nishanthvijayan/ERP#55]

**Comment by jainendra** [comment]
Suggestion : https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by nishanthvijayan** [comment]
https://eonasdan.github.io/bootstrap-datetimepicker/ required moment.js to function!
I'm not sure if the footprint is worth it.

**Comment by nishanthvijayan** [comment]
Closed via #71
